import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Play, Send, AlertTriangle } from 'lucide-react';
import Editor from '@monaco-editor/react';
import TopBar from '../components/TopBar';
import { useTimer } from '../hooks/useTimer';
import { useAssessment } from '../context/AssessmentContext';

// AI-generated code with intentional bugs
const AUDIT_PROBLEM = {
  title: 'Prime Number Checker',
  description: `The code below was generated by an AI system and may contain logical flaws or inefficiencies.

Your task:
- Identify any logical errors or bugs
- Fix inefficient algorithms
- Improve code readability
- Ensure edge cases are handled`,
  
  buggyCode: {
    python: `def is_prime(n):
    """Check if a number is prime"""
    if n <= 1:
        return False
    
    # Bug 1: Inefficient - checking all numbers up to n
    for i in range(2, n):
        if n % i == 0:
            return False
    
    return True

def find_primes(limit):
    """Find all prime numbers up to limit"""
    primes = []
    
    # Bug 2: Off-by-one error - should be range(2, limit + 1)
    for num in range(2, limit):
        if is_prime(num):
            primes.append(num)
    
    return primes

# Bug 3: No handling of negative inputs
result = find_primes(20)
print(result)`,
    
    javascript: `function isPrime(n) {
    // Bug 1: Missing check for n === 2
    if (n <= 1) {
        return false;
    }
    
    // Bug 2: Inefficient - checking all numbers up to n
    for (let i = 2; i < n; i++) {
        if (n % i === 0) {
            return false;
        }
    }
    
    return true;
}

function findPrimes(limit) {
    const primes = [];
    
    // Bug 3: Off-by-one error
    for (let num = 2; num < limit; num++) {
        if (isPrime(num)) {
            primes.push(num);
        }
    }
    
    return primes;
}

// Bug 4: No input validation
console.log(findPrimes(20));`
  },

  knownIssues: [
    {
      id: 1,
      severity: 'high',
      type: 'efficiency',
      description: 'Inefficient prime checking - should only check up to sqrt(n)',
      lineRange: [6, 9]
    },
    {
      id: 2,
      severity: 'medium',
      type: 'logic',
      description: 'Off-by-one error in range - excludes the limit itself',
      lineRange: [14, 15]
    },
    {
      id: 3,
      severity: 'low',
      type: 'validation',
      description: 'Missing input validation for negative numbers',
      lineRange: [1, 3]
    }
  ],

  testCases: [
    { input: 17, expected: true, description: 'Should return true for prime 17' },
    { input: 20, expected: false, description: 'Should return false for composite 20' },
    { input: 2, expected: true, description: 'Should handle edge case 2' },
    { input: 1, expected: false, description: 'Should return false for 1' }
  ]
};

export default function AuditScreen() {
  const navigate = useNavigate();
  const { markStageComplete, saveStageData } = useAssessment();
  const { formatTime, seconds, start } = useTimer(true);
  
  const [language, setLanguage] = useState('python');
  const [code, setCode] = useState(AUDIT_PROBLEM.buggyCode.python);
  const [originalCode] = useState(AUDIT_PROBLEM.buggyCode.python);
  const [output, setOutput] = useState([]);
  const [isRunning, setIsRunning] = useState(false);
  const [hasSubmitted, setHasSubmitted] = useState(false);
  
  // Behavioral tracking for audit
  const [editCount, setEditCount] = useState(0);
  const [linesChanged, setLinesChanged] = useState(new Set());
  const [editHistory, setEditHistory] = useState([]);
  const sessionStartTime = useRef(Date.now());
  const previousCode = useRef(code);

  useEffect(() => {
    start();
  }, []);

  const handleLanguageChange = (e) => {
    const newLang = e.target.value;
    setLanguage(newLang);
    setCode(AUDIT_PROBLEM.buggyCode[newLang]);
    previousCode.current = AUDIT_PROBLEM.buggyCode[newLang];
  };

  const handleEditorChange = (value) => {
    if (!value) return;
    
    setCode(value);
    setEditCount(prev => prev + 1);
    
    // Track which lines were changed
    const oldLines = previousCode.current.split('\n');
    const newLines = value.split('\n');
    const changed = new Set(linesChanged);
    
    newLines.forEach((line, idx) => {
      if (oldLines[idx] !== line) {
        changed.add(idx + 1);
      }
    });
    
    setLinesChanged(changed);
    
    // Track edit event
    setEditHistory(prev => [...prev, {
      timestamp: Date.now() - sessionStartTime.current,
      linesChanged: changed.size,
      codeLength: value.length
    }]);
    
    previousCode.current = value;
  };

  const handleTest = async () => {
    setIsRunning(true);
    
    // Simulate code testing
    setTimeout(() => {
      // Simple analysis - check if key improvements were made
      const improvedEfficiency = code.includes('sqrt') || code.includes('**0.5') || code.includes('Math.sqrt');
      const fixedRange = code.includes('limit + 1') || code.includes('limit)') && code.split('range').length > 1;
      const hasValidation = code.includes('< 0') || code.includes('negative');
      
      const results = [
        {
          test: 'Functional Tests',
          passed: 3,
          total: 4,
          status: 'warning',
          message: 'Most test cases pass, but edge cases may fail'
        },
        {
          test: 'Performance Analysis',
          passed: improvedEfficiency,
          status: improvedEfficiency ? 'success' : 'error',
          message: improvedEfficiency 
            ? 'Good! Optimized to O(√n) complexity' 
            : '⚠️ Still checking all numbers up to n - inefficient for large inputs'
        },
        {
          test: 'Edge Case Handling',
          passed: fixedRange,
          status: fixedRange ? 'success' : 'warning',
          message: fixedRange 
            ? 'Range issue fixed' 
            : '⚠️ Off-by-one error still present'
        },
        {
          test: 'Input Validation',
          passed: hasValidation,
          status: hasValidation ? 'success' : 'info',
          message: hasValidation 
            ? 'Input validation added' 
            : 'ℹ️ Consider adding validation for negative inputs'
        }
      ];
      
      setOutput(results);
      setIsRunning(false);
    }, 1500);
  };

  const calculateAuditScore = () => {
    // Calculate how well the audit was performed
    const bugsFixed = output.filter(r => r.passed === true).length;
    const totalBugs = AUDIT_PROBLEM.knownIssues.length;
    
    // Calculate edit precision (fewer edits = more precise)
    const editEfficiency = Math.max(0, 100 - (editCount * 2));
    
    return {
      bugsFixed,
      totalBugs,
      bugFixRate: (bugsFixed / totalBugs) * 100,
      linesModified: linesChanged.size,
      editEfficiency: Math.min(100, editEfficiency),
      overallScore: ((bugsFixed / totalBugs) * 70) + (Math.min(100, editEfficiency) * 0.3)
    };
  };

  const handleSubmit = () => {
    const auditMetrics = calculateAuditScore();
    
    const auditData = {
      problem: AUDIT_PROBLEM.title,
      language,
      originalCode: AUDIT_PROBLEM.buggyCode[language],
      auditedCode: code,
      totalTime: seconds,
      editCount,
      linesChanged: Array.from(linesChanged),
      editHistory,
      knownIssues: AUDIT_PROBLEM.knownIssues,
      testResults: output,
      metrics: auditMetrics,
      completedAt: new Date().toISOString()
    };

    saveStageData('audit', auditData);
    markStageComplete('audit');
    setHasSubmitted(true);
    
    // Navigate to results page after 2 seconds
    setTimeout(() => {
      navigate('/results');
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <TopBar currentStage={3} showTimer={true} timeElapsed={formatTime()} />
      
      <div className="flex h-[calc(100vh-64px)]">
        {/* Left Panel - Instructions */}
        <div className="w-2/5 bg-white border-r border-slate-200 overflow-y-auto">
          <div className="p-6">
            <div className="flex items-center gap-2 mb-4">
              <div className="bg-purple-100 p-2 rounded">
                <Search className="text-purple-600" size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-800">Logic Audit</h2>
            </div>
            
            <div className="bg-purple-50 border-l-4 border-purple-600 p-3 mb-6">
              <p className="text-sm text-purple-800 font-semibold">Stage C: Supervisor Mode</p>
            </div>

            {/* Warning */}
            <div className="bg-amber-50 border border-amber-200 p-4 rounded-lg mb-6">
              <div className="flex items-start gap-3">
                <AlertTriangle className="text-amber-600 mt-0.5 flex-shrink-0" size={20} />
                <div>
                  <p className="text-amber-900 font-semibold mb-1">AI-Generated Code Review</p>
                  <p className="text-sm text-amber-800">
                    The code contains logical flaws and inefficiencies. Your task is to identify and fix them.
                  </p>
                </div>
              </div>
            </div>

            {/* Task Instructions */}
            <div className="mb-6">
              <h3 className="text-lg font-bold text-slate-800 mb-3">
                Task: {AUDIT_PROBLEM.title}
              </h3>
              <p className="text-slate-700 whitespace-pre-line leading-relaxed mb-4">
                {AUDIT_PROBLEM.description}
              </p>
            </div>

            {/* Known Issues (Hidden in real scenario - shown here for demo) */}
            <div className="mb-6">
              <h4 className="font-semibold text-slate-800 mb-3 flex items-center gap-2">
                <span>Issues to Find</span>
                <span className="text-xs bg-slate-200 text-slate-600 px-2 py-0.5 rounded">
                  {AUDIT_PROBLEM.knownIssues.length} known issues
                </span>
              </h4>
              <div className="space-y-2">
                {AUDIT_PROBLEM.knownIssues.map((issue) => (
                  <div 
                    key={issue.id}
                    className={`p-3 rounded-lg border-l-4 ${
                      issue.severity === 'high' 
                        ? 'bg-red-50 border-red-500' 
                        : issue.severity === 'medium'
                        ? 'bg-amber-50 border-amber-500'
                        : 'bg-blue-50 border-blue-500'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className={`text-xs font-semibold uppercase ${
                        issue.severity === 'high' 
                          ? 'text-red-700' 
                          : issue.severity === 'medium'
                          ? 'text-amber-700'
                          : 'text-blue-700'
                      }`}>
                        {issue.severity} - {issue.type}
                      </span>
                      <span className="text-xs text-slate-500">
                        Lines {issue.lineRange[0]}-{issue.lineRange[1]}
                      </span>
                    </div>
                    <p className="text-sm text-slate-700">{issue.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Expected Test Cases */}
            <div className="mb-6">
              <h4 className="font-semibold text-slate-800 mb-3">Test Cases:</h4>
              <div className="space-y-2">
                {AUDIT_PROBLEM.testCases.map((test, idx) => (
                  <div key={idx} className="bg-slate-50 p-3 rounded border border-slate-200">
                    <div className="font-mono text-sm text-slate-800 mb-1">
                      Input: {test.input} → Expected: {test.expected.toString()}
                    </div>
                    <div className="text-xs text-slate-600">{test.description}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Audit Metrics */}
            <div className="mt-8 pt-6 border-t border-slate-200">
              <h4 className="font-semibold text-slate-800 mb-3 text-sm">Audit Metrics</h4>
              <div className="grid grid-cols-2 gap-3 text-xs">
                <div className="bg-slate-50 p-3 rounded">
                  <div className="text-slate-600">Edits Made</div>
                  <div className="text-lg font-bold text-slate-800">{editCount}</div>
                </div>
                <div className="bg-slate-50 p-3 rounded">
                  <div className="text-slate-600">Lines Changed</div>
                  <div className="text-lg font-bold text-slate-800">{linesChanged.size}</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Panel - Code Editor */}
        <div className="w-3/5 flex flex-col bg-slate-900">
          {/* Editor Header */}
          <div className="bg-slate-800 px-4 py-3 flex items-center justify-between border-b border-slate-700">
            <div className="flex items-center gap-3">
              <select 
                value={language}
                onChange={handleLanguageChange}
                className="bg-slate-700 text-white px-3 py-1.5 rounded text-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
              >
                <option value="python">Python</option>
                <option value="javascript">JavaScript</option>
              </select>
              <span className="text-slate-400 text-sm">
                Problem: {AUDIT_PROBLEM.title}
              </span>
            </div>
            
            <div className="flex gap-2">
              <button 
                onClick={handleTest}
                disabled={isRunning || hasSubmitted}
                className="flex items-center gap-2 bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Play size={16} />
                {isRunning ? 'Testing...' : 'Test'}
              </button>
              <button 
                onClick={handleSubmit}
                disabled={output.length === 0 || hasSubmitted}
                className="flex items-center gap-2 bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Send size={16} />
                {hasSubmitted ? 'Submitted!' : 'Submit Audit'}
              </button>
            </div>
          </div>

          {/* Monaco Editor */}
          <div className="flex-1 overflow-hidden">
            <Editor
              height="100%"
              language={language}
              value={code}
              onChange={handleEditorChange}
              theme="vs-dark"
              options={{
                minimap: { enabled: true },
                fontSize: 14,
                lineNumbers: 'on',
                scrollBeyondLastLine: false,
                automaticLayout: true,
                tabSize: 4,
                wordWrap: 'on',
                glyphMargin: true
              }}
            />
          </div>

          {/* Test Results */}
          <div className="bg-slate-800 p-4 border-t border-slate-700 h-48 overflow-y-auto">
            <div className="text-xs text-slate-400 mb-2 font-semibold">Analysis Results:</div>
            <div className="space-y-2">
              {output.length === 0 ? (
                <div className="text-slate-500 text-sm">
                  Click "Test" to analyze your fixes...
                </div>
              ) : (
                output.map((result, idx) => (
                  <div 
                    key={idx} 
                    className={`p-3 rounded ${
                      result.status === 'success' 
                        ? 'bg-green-900 bg-opacity-30 border border-green-700' 
                        : result.status === 'error'
                        ? 'bg-red-900 bg-opacity-30 border border-red-700'
                        : result.status === 'warning'
                        ? 'bg-amber-900 bg-opacity-30 border border-amber-700'
                        : 'bg-blue-900 bg-opacity-30 border border-blue-700'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className={`font-semibold text-sm ${
                        result.status === 'success' ? 'text-green-400' 
                        : result.status === 'error' ? 'text-red-400'
                        : result.status === 'warning' ? 'text-amber-400'
                        : 'text-blue-400'
                      }`}>
                        {result.test}
                      </span>
                      {result.passed !== undefined && typeof result.passed === 'number' && (
                        <span className="text-xs text-slate-300">
                          {result.passed}/{result.total}
                        </span>
                      )}
                    </div>
                    <div className="text-sm text-slate-300">{result.message}</div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Success Modal */}
      {hasSubmitted && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-8 max-w-md text-center">
            <div className="mb-4">
              <div className="inline-block bg-purple-100 p-4 rounded-full">
                <Search className="text-purple-600" size={48} />
              </div>
            </div>
            <h3 className="text-2xl font-bold text-slate-800 mb-2">Audit Complete!</h3>
            <p className="text-slate-600 mb-4">
              Your audit has been submitted. Generating your results...
            </p>
            <div className="bg-slate-50 p-4 rounded-lg">
              <div className="text-sm text-slate-600 mb-2">Bugs Fixed:</div>
              <div className="text-3xl font-bold text-purple-600">
                {output.filter(r => r.passed === true).length} / {AUDIT_PROBLEM.knownIssues.length}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}